SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[animals](
	[id] [uniqueidentifier] NOT NULL,
	[species] [varchar](32) NOT NULL,
	[breed] [varchar](32) NULL,
	[gender] [bit] NOT NULL,
	[age] [int] NULL,
	[infirm] [bit] NULL,
	[vaccinated] [bit] NULL,
	[shelter_id] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[animals] ADD PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[animals]  WITH CHECK ADD  CONSTRAINT [shelter_id] FOREIGN KEY([shelter_id])
REFERENCES [dbo].[shelters] ([id])
GO
ALTER TABLE [dbo].[animals] CHECK CONSTRAINT [shelter_id]
GO

INSERT INTO animals (id, species, breed, gender, age, infirm, vaccinated)
VALUES 
    (NEWID(), 'cat', 'mainecoon', 0, 18, 0, 0),
    (NEWID(), 'cat', 'british', 0, 13, 0, 0),
    (NEWID(), 'cat', 'abyssinian', 0, 17, 0, 1),
    (NEWID(), 'cat', 'abyssinian', 1, 4, 0, 0),
    (NEWID(), 'cat', 'bobtail', 1, 0, 1, 0),
    (NEWID(), 'cat', 'british', 1, 4, 0, 0),
    (NEWID(), 'cat', 'british', 1, 9, 1, 1),
    (NEWID(), 'cat', 'british', 1, 2, 0, 0),
    (NEWID(), 'cat', 'mainecoon', 1, 4, 0, 0),
    (NEWID(), 'cat', 'bobtail', 0, 20, 0, 1),
    (NEWID(), 'cat', 'scottish', 0, 15, 1, 1),
    (NEWID(), 'cat', 'bobtail', 0, 9, 0, 0),
    (NEWID(), 'cat', 'abyssinian', 1, 4, 0, 0),
    (NEWID(), 'cat', 'british', 1, 8, 0, 0),
    (NEWID(), 'cat', 'abyssinian', 0, 2, 1, 1),
    (NEWID(), 'cat', 'british', 0, 17, 0, 1),
    (NEWID(), 'cat', 'british', 0, 3, 0, 1),
    (NEWID(), 'cat', 'abyssinian', 1, 2, 0, 0),
    (NEWID(), 'cat', 'none', 0, 6, 0, 0),
    (NEWID(), 'cat', 'bobtail', 0, 11, 1, 0),
    (NEWID(), 'cat', 'scottish', 1, 17, 0, 0),
    (NEWID(), 'cat', 'mainecoon', 1, 18, 1, 1),
    (NEWID(), 'cat', 'british', 1, 1, 0, 0),
    (NEWID(), 'cat', 'bobtail', 0, 5, 1, 1),
    (NEWID(), 'cat', 'abyssinian', 1, 3, 0, 0),
    (NEWID(), 'cat', 'none', 0, 17, 0, 1),
    (NEWID(), 'cat', 'abyssinian', 0, 12, 0, 0),
    (NEWID(), 'cat', 'scottish', 1, 17, 1, 1),
    (NEWID(), 'cat', 'mainecoon', 1, 10, 1, 1),
    (NEWID(), 'cat', 'bobtail', 0, 1, 0, 0),
    (NEWID(), 'cat', 'bobtail', 0, 15, 1, 1),
    (NEWID(), 'cat', 'bobtail', 1, 15, 1, 1),
    (NEWID(), 'cat', 'mainecoon', 0, 15, 0, 1),
    (NEWID(), 'cat', 'none', 1, 5, 1, 0),
    (NEWID(), 'cat', 'mainecoon', 1, 3, 0, 0),
    (NEWID(), 'cat', 'british', 1, 4, 0, 1),
    (NEWID(), 'cat', 'british', 0, 12, 0, 1),
    (NEWID(), 'cat', 'scottish', 0, 1, 0, 1),
    (NEWID(), 'cat', 'bobtail', 0, 5, 1, 0),
    (NEWID(), 'cat', 'bobtail', 0, 18, 0, 1),
    (NEWID(), 'cat', 'none', 0, 17, 0, 1),
    (NEWID(), 'cat', 'none', 0, 2, 0, 0),
    (NEWID(), 'cat', 'abyssinian', 1, 18, 0, 1),
    (NEWID(), 'cat', 'bobtail', 1, 19, 0, 0),
    (NEWID(), 'cat', 'british', 1, 19, 1, 1),
    (NEWID(), 'cat', 'scottish', 0, 1, 0, 1),
    (NEWID(), 'cat', 'none', 1, 10, 0, 0),
    (NEWID(), 'cat', 'abyssinian', 0, 20, 0, 1),
    (NEWID(), 'cat', 'scottish', 1, 10, 1, 1),
    (NEWID(), 'cat', 'bobtail', 1, 12, 1, 0),
    (NEWID(), 'dog', 'none', 1, 13, 0, 0),
    (NEWID(), 'dog', 'none', 1, 12, 0, 1),
    (NEWID(), 'dog', 'terrier', 0, 11, 0, 0),
    (NEWID(), 'dog', 'collie', 1, 12, 1, 0),
    (NEWID(), 'dog', 'none', 0, 20, 1, 0),
    (NEWID(), 'dog', 'terrier', 1, 2, 0, 0),
    (NEWID(), 'dog', 'spaniel', 1, 1, 0, 0),
    (NEWID(), 'dog', 'foxhound', 0, 19, 1, 1),
    (NEWID(), 'dog', 'corgi', 0, 9, 1, 1),
    (NEWID(), 'dog', 'spaniel', 0, 14, 0, 0),
    (NEWID(), 'dog', 'corgi', 1, 18, 1, 1),
    (NEWID(), 'dog', 'corgi', 0, 3, 1, 0),
    (NEWID(), 'dog', 'terrier', 1, 18, 1, 1),
    (NEWID(), 'dog', 'collie', 1, 18, 1, 0),
    (NEWID(), 'dog', 'corgi', 1, 5, 1, 0),
    (NEWID(), 'dog', 'terrier', 1, 14, 0, 0),
    (NEWID(), 'dog', 'foxhound', 1, 0, 1, 0),
    (NEWID(), 'dog', 'spaniel', 0, 20, 1, 0),
    (NEWID(), 'dog', 'spaniel', 1, 17, 0, 1),
    (NEWID(), 'dog', 'terrier', 0, 6, 0, 1),
    (NEWID(), 'dog', 'terrier', 1, 1, 1, 0),
    (NEWID(), 'dog', 'foxhound', 0, 12, 0, 1),
    (NEWID(), 'dog', 'spaniel', 1, 0, 0, 1),
    (NEWID(), 'dog', 'collie', 0, 9, 0, 0),
    (NEWID(), 'dog', 'none', 1, 12, 1, 0),
    (NEWID(), 'dog', 'spaniel', 1, 16, 1, 1),
    (NEWID(), 'dog', 'collie', 1, 12, 0, 1),
    (NEWID(), 'dog', 'terrier', 0, 10, 1, 1),
    (NEWID(), 'dog', 'foxhound', 1, 12, 1, 1),
    (NEWID(), 'dog', 'foxhound', 0, 12, 1, 0),
    (NEWID(), 'dog', 'foxhound', 1, 0, 1, 0),
    (NEWID(), 'dog', 'corgi', 1, 0, 1, 1),
    (NEWID(), 'dog', 'none', 1, 13, 1, 1),
    (NEWID(), 'dog', 'terrier', 0, 19, 1, 1),
    (NEWID(), 'dog', 'none', 0, 9, 0, 0),
    (NEWID(), 'dog', 'none', 1, 6, 1, 0),
    (NEWID(), 'dog', 'spaniel', 1, 15, 1, 1),
    (NEWID(), 'dog', 'corgi', 0, 13, 1, 1),
    (NEWID(), 'dog', 'foxhound', 0, 0, 0, 0),
    (NEWID(), 'dog', 'none', 1, 11, 1, 0),
    (NEWID(), 'dog', 'foxhound', 0, 14, 0, 1),
    (NEWID(), 'dog', 'spaniel', 1, 13, 1, 1),
    (NEWID(), 'dog', 'spaniel', 0, 4, 0, 1),
    (NEWID(), 'dog', 'spaniel', 1, 5, 1, 1),
    (NEWID(), 'dog', 'corgi', 1, 4, 1, 0),
    (NEWID(), 'dog', 'none', 1, 14, 1, 1),
    (NEWID(), 'dog', 'none', 0, 18, 0, 1),
    (NEWID(), 'dog', 'spaniel', 0, 9, 0, 0),
    (NEWID(), 'dog', 'corgi', 0, 15, 1, 1),
    (NEWID(), 'dog', 'terrier', 1, 11, 1, 0);
​
